Repository elastic/elastic-transport-ruby, pull requests merged in 2022-08, with the labels that each got.

#31 Grab all headers from `header_str` when using `Curb`
  lib/elastic/transport/transport/http/curb.rb
  test/integration/transport_test.rb
  test/unit/transport_curb_test.rb
Labels: bug

#33 [CI] Updates GitHub Action
  .github/workflows/tests.yml
Labels: CI

#35 Updates adapters detection for Faraday
  lib/elastic/transport/client.rb
Labels: faraday
